name: Publish Lua types
on:
  workflow_dispatch:
  push:
    tags: 'dota-lua-types@*'

permissions:
  id-token: write # Required for trusted publishing
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@moddota'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        working-directory: packages/dota-lua-types
